# Initial publish date — used to decide 'NEW' badge threshold.
date: 2026-04-13
url: /learn/topic-3-api-microservices/
draft: false
title: i18n.courses.topic_3_api_microservices.title
description: i18n.courses.topic_3_api_microservices.description
logo: '/images/courses/topic-3-api-microservices/logo.svg'
background: '/images/courses/topic-3-api-microservices/background.svg'
card: '/images/courses/topic-3-api-microservices/card.svg'
type: tech
highlight: 'red'
