# Initial publish date — used to decide 'NEW' badge threshold.
date: 2026-04-17
url: /learn/pronunciation-guide/
draft: false
title: i18n.courses.pronunciation_guide.title
description: i18n.courses.pronunciation_guide.description
logo: '/images/courses/pronunciation-guide/logo.svg'
background: '/images/courses/pronunciation-guide/background.svg'
card: '/images/courses/pronunciation-guide/card.svg'
type: english
highlight: 'orange'
