title: i18n.courses.topic_19_ai_ml_security.title
description: i18n.courses.topic_19_ai_ml_security.description
highlight: coral
type: tech
hero:
  image: "image/admin/default.svg"
  alt: "Topic 19 AI/ML Security"
