# Initial publish date — used to decide 'NEW' badge threshold.
date: 2026-04-13
url: /learn/topic-5-ai-ml-pipelines/
draft: false
title: i18n.courses.topic_5_ai_ml_pipelines.title
description: i18n.courses.topic_5_ai_ml_pipelines.description
logo: '/images/courses/topic-5-ai-ml-pipelines/logo.svg'
background: '/images/courses/topic-5-ai-ml-pipelines/background.svg'
card: '/images/courses/topic-5-ai-ml-pipelines/card.svg'
type: tech
highlight: 'violet'
