# Initial publish date — used to decide 'NEW' badge threshold.
date: 2026-04-19
url: /learn/topic-15-en-reading-lab/
draft: false
title: i18n.courses.topic_15_en_reading_lab.title
description: i18n.courses.topic_15_en_reading_lab.description
logo: '/images/courses/topic-15-en-reading-lab/logo.svg'
background: '/images/courses/topic-15-en-reading-lab/background.svg'
card: '/images/courses/topic-15-en-reading-lab/card.svg'
highlight: 'emerald'
